defaults: &defaults
  github:
    key: "your_github_key"
    secret: "your_github_secret"

  twitter:
    key: "your_twitter_key"
    secret: "your_twitter_secret"

  facebook:
    key: "your_facebook_key"
    secret: "your_facebook_secret"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
